alias: Christmas Garage Lights
triggers:
  - entity_id: light.coach_light_1
    from:
      - "off"
      - unavailable
    to: "on"
    trigger: state
  - entity_id: light.coach_light_2
    from:
      - "off"
      - unavailable
    to: "on"
    trigger: state
  - entity_id: light.coach_light_3
    from:
      - "off"
      - unavailable
    to: "on"
    trigger: state
conditions: []
variables:
  start_date:
    month: 11
    day: 30
  end_date:
    month: 1
    day: 3
  color_1: [255, 0, 0]
  color_2: [255, 255, 255]
  color_3: [0, 255, 0]
  in_holiday_range: >
    {% set cm, cd = now().month, now().day %} {% set sm, sd = start_date.month,
    start_date.day %} {% set em, ed = end_date.month, end_date.day %}

    {% if sm > em %}
      {{ (cm > sm or (cm == sm and cd >= sd)) or (cm < em or (cm == em and cd <= ed)) }}
    {% elif sm == em %}
      {{ cm == sm and sd <= cd <= ed }}
    {% else %}
      {{ (cm > sm or (cm == sm and cd >= sd)) and (cm < em or (cm == em and cd <= ed)) }}
    {% endif %}
  is_reset_day: >
    {% set n = now() + timedelta(days=1) %} {% set em, ed = end_date.month,
    end_date.day %} {{ n.month == em and n.day == ed }}
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ in_holiday_range }}"
        sequence:
          - repeat:
              for_each:
                - light: light.coach_light_1
                  color: "{{ color_1 }}"
                - light: light.coach_light_2
                  color: "{{ color_2 }}"
                - light: light.coach_light_3
                  color: "{{ color_3 }}"
              sequence:
                - target:
                    entity_id: "{{ repeat.item.light }}"
                  data:
                    rgb_color: "{{ repeat.item.color }}"
                    brightness_pct: 100
                  action: light.turn_on
      - conditions:
          - condition: template
            value_template: "{{ is_reset_day }}"
        sequence:
          - repeat:
              for_each:
                - light.coach_light_1
                - light.coach_light_2
                - light.coach_light_3
              sequence:
                - target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    color_temp: 370
                    brightness_pct: 50
                  action: light.turn_on
mode: single
