alias: Office Light Weekday Schedule
description: Turn on office light at 9am if home; turn off at 5pm if on.
triggers:
  - at: "09:00:00"
    platform: time 
  - at: "17:00:00"
    platform: time 
conditions: [] 
actions:
  - choose:
      - conditions:
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
          - condition: template
            value_template: "{{ now().hour == 9 and now().minute == 0 }}"
          - condition: state
            entity_id: person.jason
            state: home
        sequence:
          - service: switch.turn_on 
            target:
              entity_id: switch.office_light
      - conditions:
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
          - condition: template
            value_template: "{{ now().hour == 17 and now().minute == 0 }}" 
          - condition: state
            entity_id: switch.office_light
            state: "on"
        sequence:
          - service: switch.turn_off 
            target:
              entity_id: switch.office_light
mode: single
