blueprint:
  name: Holiday Lighting Schedule (Sunset & Optional Lights)
  description: Change light colors between two dates at sunset and reset afterward. Works with 1–3 lights.
  domain: automation
  input:
    light_1:
      name: Light 1 (e.g. Red)
      default: ''
      selector:
        entity:
          domain: light
          multiple: false
    light_1_color:
      name: Light 1 RGB Color
      default: [255, 0, 0]
      selector:
        color_rgb: {}

    light_2:
      name: Light 2 (e.g. White)
      default: ''
      selector:
        entity:
          domain: light
          multiple: false
    light_2_color:
      name: Light 2 RGB Color
      default: [255, 255, 255]
      selector:
        color_rgb: {}

    light_3:
      name: Light 3 (e.g. Blue)
      default: ''
      selector:
        entity:
          domain: light
          multiple: false
    light_3_color:
      name: Light 3 RGB Color
      default: [0, 0, 255]
      selector:
        color_rgb: {}

    start_date:
      name: Start Date
      selector:
        date: {}

    end_date:
      name: End Date
      selector:
        date: {}

    reset_color_temp:
      name: Reset Color Temperature (mireds)
      default: 370
      selector:
        number:
          min: 150
          max: 500
          unit_of_measurement: mireds

    sunset_offset:
      name: Sunset Offset (HH:MM:SS)
      description: 'Offset from sunset for the primary trigger. E.g., +00:15:00 for 15 mins after sunset.'
      default: '+00:00:00'
      selector:
        text: {}

    enable_light_on_trigger:
      name: Enable Light On Trigger
      description: 'If enabled, the automation will also trigger when any of the selected lights turn on, to ensure colors are applied.'
      default: true
      selector:
        boolean: {}

    brightness_pct:
      name: Holiday Brightness (%)
      description: 'Brightness percentage for holiday colors (1-100).'
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: '%'
          mode: slider # Makes it a slider in the UI

    reset_brightness_pct:
      name: Reset Brightness (%)
      description: 'Brightness percentage for reset color (1-100).'
      default: 50
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: '%'
          mode: slider # Makes it a slider in the UI


trigger:
  - platform: sun
    event: sunset
    offset: !input sunset_offset
  - platform: state
    entity_id: >
      {% set entities = [] %}
      {% if inputs.light_1 != '' %}
        {% set entities = entities + [inputs.light_1] %}
      {% endif %}
      {% if inputs.light_2 != '' %}
        {% set entities = entities + [inputs.light_2] %}
      {% endif %}
      {% if inputs.light_3 != '' %}
        {% set entities = entities + [inputs.light_3] %}
      {% endif %}
      {{ entities }}
    from: "off"
    to: "on"
    enabled: "{{ inputs.enable_light_on_trigger }}"

condition:
  - condition: or
    conditions:
      - condition: template
        value_template: >
          {{ now().date() >= strptime(inputs.start_date, "%Y-%m-%d").date()
            and now().date() <= strptime(inputs.end_date, "%Y-%m-%d").date() }}
      - condition: template
        value_template: >
          {{ now().date() == (strptime(inputs.end_date, "%Y-%m-%d").date() + timedelta(days=1)) }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ now().date() >= strptime(inputs.start_date, "%Y-%m-%d").date()
                and now().date() <= strptime(inputs.end_date, "%Y-%m-%d").date() }}
        sequence:
          - if: "{{ inputs.light_1 != '' }}"
            then:
              - service: light.turn_on
                target:
                  entity_id: !input light_1
                data:
                  rgb_color: !input light_1_color
                  brightness_pct: !input brightness_pct

          - if: "{{ inputs.light_2 != '' }}"
            then:
              - service: light.turn_on
                target:
                  entity_id: !input light_2
                data:
                  rgb_color: !input light_2_color
                  brightness_pct: !input brightness_pct

          - variables:
              target_entities: >
                {% set entities = [] %}
                {% if inputs.light_3 != '' %}
                  {% set entities = entities + [inputs.light_3] %}
                {% endif %}
                {{ entities }}
            if: "{{ target_entities | length > 0 }}"
            then:
              - service: light.turn_on
                target:
                  entity_id: "{{ target_entities }}"
                data:
                  rgb_color: !input light_3_color
                  brightness_pct: !input brightness_pct

      - conditions:
          - condition: template
            value_template: >
              {{ now().date() == (strptime(inputs.end_date, "%Y-%m-%d").date() + timedelta(days=1)) }}
        sequence:
          - if: "{{ inputs.light_1 != '' }}"
            then:
              - service: light.turn_on
                target:
                  entity_id: !input light_1
                data:
                  color_temp: !input reset_color_temp
                  brightness_pct: !input reset_brightness_pct

          - if: "{{ inputs.light_2 != '' }}"
            then:
              - service: light.turn_on
                target:
                  entity_id: !input light_2
                data:
                  color_temp: !input reset_color_temp
                  brightness_pct: !input reset_brightness_pct

          - if: "{{ inputs.light_3 != '' }}"
            then:
              - service: light.turn_on
                target:
                  entity_id: !input light_3
                data:
                  color_temp: !input reset_color_temp
                  brightness_pct: !input reset_brightness_pct
mode: single
