blueprint:
  name: Holiday Lighting Schedule (Sunset & Optional Lights)
  description: Change light colors between two dates at sunset and reset afterward. Works with 1–3 lights.
  domain: automation
  input:
    light_1:
      name: Light 1 (e.g. Red)
      default: ''
      selector:
        entity:
          domain: light
          multiple: false
    light_1_color:
      name: Light 1 RGB Color
      default: [255, 0, 0]
      selector:
        color_rgb: {}

    light_2:
      name: Light 2 (e.g. White)
      default: ''
      selector:
        entity:
          domain: light
          multiple: false
    light_2_color:
      name: Light 2 RGB Color
      default: [255, 255, 255]
      selector:
        color_rgb: {}

    light_3:
      name: Light 3 (e.g. Blue)
      default: ''
      selector:
        entity:
          domain: light
          multiple: false
    light_3_color:
      name: Light 3 RGB Color
      default: [0, 0, 255]
      selector:
        color_rgb: {}

    start_month_day:
      name: Start Month/Day (MM-DD)
      description: 'The month and day to start the holiday lights each year (e.g., 11-30 for Nov 30).'
      selector:
        text: {}

    end_month_day:
      name: End Month/Day (MM-DD)
      description: 'The month and day to end the holiday lights each year (e.g., 01-03 for Jan 3).'
      selector:
        text: {}

    reset_color_temp:
      name: Reset Color Temperature (mireds)
      default: 300
      selector:
        number:
          min: 150
          max: 500
          unit_of_measurement: mireds

    brightness_pct:
      name: Holiday Brightness (%)
      description: 'Brightness percentage for holiday colors (1-100).'
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: '%'
          mode: slider

    reset_brightness_pct:
      name: Reset Brightness (%)
      description: 'Brightness percentage for reset color (1-100).'
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: '%'
          mode: slider

variables:
  in_holiday_range: >
    {% set s = inputs.start_month_day.split('-') %} 
    {% set e = inputs.end_month_day.split('-') %} 
    {% set sm, sd = s[0] | int, s[1] | int %} 
    {% set em, ed = e[0] | int, e[1] | int %} 
    {% set cm, cd = now().month, now().day %}

    {% if sm > em %}
      {{ (cm > sm or (cm == sm and cd >= sd)) or (cm < em or (cm == em and cd <= ed)) }}
    {% elif sm == em %}
      {{ cm == sm and sd <= cd <= ed }}
    {% else %}
      {{ (cm > sm or (cm == sm and cd >= sd)) and (cm < em or (cm == em and cd <= ed)) }}
    {% endif %}
  is_reset_day: >
    {% set e = inputs.end_month_day.split('-') %} 
    {% set em, ed = e[0] | int, e[1] | int %} 
    {% set n = now() + timedelta(days=1) %} 
    {{ n.month == em and n.day == ed }}

trigger:
  - platform: state
    entity_id: 
      - !input light_1
      - !input light_2
      - !input light_3
    from: ['off', 'unavailable']
    to: "on"

conditions: []
action:
  - choose:
    - conditions: "{{ in_holiday_range }}"
      sequence:
        - repeat:
            for_each:
              - { light: !input light_1, color: !input light_1_color }
              - { light: !input light_2, color: !input light_2_color }
              - { light: !input light_3, color: !input light_3_color }
            sequence:
              - service: light.turn_on
                target:
                  entity_id: "{{ repeat.item.light }}"
                data:
                  rgb_color: "{{ repeat.item.color }}"
                  brightness_pct: !input brightness_pct
    - conditions: "{{ is_reset_day }}"
      sequence:
        - repeat:
            for_each:
              - !input light_1
              - !input light_2
              - !input light_3
            sequence:
              - service: light.turn_on
                target:
                  entity_id: "{{ repeat.item }}"
                data:
                  color_temp: !input reset_color_temp
                  brightness_pct: !input reset_brightness_pct
mode: single
